CREATE TABLE IF NOT EXISTS doctor (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    job VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS patient (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS slots (
    doctorid INTEGER  NOT NULL,
    time TIMESTAMP NOT NULL,
    isbooked BOOLEAN NOT NULL DEFAULT FALSE,
    patientid INTEGER,

    CONSTRAINT slots_pkey PRIMARY KEY (doctorid, time),

    CONSTRAINT slot_doc FOREIGN KEY (doctorid)
        REFERENCES doctor (id) ON DELETE CASCADE,

    CONSTRAINT slot_patient FOREIGN KEY (patientid)
        REFERENCES patient (id) ON DELETE SET NULL
);



CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS medical_knowledge_base CASCADE;

CREATE TABLE medical_knowledge_base (
    id SERIAL PRIMARY KEY,
    specialty VARCHAR(100) NOT NULL,      -- К какому врачу привязана статья
    wiki_page_title VARCHAR(255),         -- Название статьи на Википедии
    chunk_text TEXT NOT NULL,             -- Смысловой кусок текста
    embedding VECTOR(1024) NOT NULL      -- Сжатый вектор (подходит под лимиты индексов)
);


CREATE INDEX IF NOT EXISTS idx_medical_knowledge_embedding
ON medical_knowledge_base
USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_medical_knowledge_specialty
ON medical_knowledge_base (specialty);
